-- MySQL Script generated by MySQL Workbench
-- ven. 19 févr. 2021 16:26:16 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema StationAccueil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StationAccueil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StationAccueil` DEFAULT CHARACTER SET utf8 ;
USE `StationAccueil` ;

-- -----------------------------------------------------
-- Table `StationAccueil`.`Agents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`Agents` (
  `idagent` INT NOT NULL,
  `nom` VARCHAR(30) NULL DEFAULT NULL,
  `prenom` VARCHAR(30) NULL DEFAULT NULL,
  `numbadge` VARCHAR(10) NULL DEFAULT NULL,
  `statut` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idagent`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`Rondes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`Rondes` (
  `idronde` INT NOT NULL,
  `nom` VARCHAR(30) NULL DEFAULT NULL,
  `statut` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idronde`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`AEteEffectueePar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`AEteEffectueePar` (
  `idronde` INT NOT NULL,
  `idagent` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `heure` TIME(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idronde`, `idagent`),
  INDEX `idagent` (`idagent` ASC),
  CONSTRAINT `AETEEFFECTUEEPAR_ibfk_1`
    FOREIGN KEY (`idagent`)
    REFERENCES `StationAccueil`.`Agents` (`idagent`),
  CONSTRAINT `AETEEFFECTUEEPAR_ibfk_2`
    FOREIGN KEY (`idronde`)
    REFERENCES `StationAccueil`.`Rondes` (`idronde`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`Anomalies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`Anomalies` (
  `idanomalie` INT NOT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  `photos` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idanomalie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`Pointeaux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`Pointeaux` (
  `idpointeau` INT NOT NULL,
  `designation` VARCHAR(30) NULL DEFAULT NULL,
  `statut` TINYINT(1) NULL DEFAULT NULL,
  `tag_mifare` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idpointeau`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`AEteScanne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`AEteScanne` (
  `idpointeau` INT NOT NULL,
  `idagent` INT NOT NULL,
  `idronde` INT NOT NULL,
  `idanomalie` INT NOT NULL,
  `ordre` INT NULL DEFAULT NULL,
  `temps` TIME(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idpointeau`, `idagent`, `idronde`, `idanomalie`),
  INDEX `idanomalie` (`idanomalie` ASC),
  INDEX `idronde` (`idronde` ASC),
  INDEX `idagent` (`idagent` ASC),
  CONSTRAINT `AETESCANNE_ibfk_1`
    FOREIGN KEY (`idanomalie`)
    REFERENCES `StationAccueil`.`Anomalies` (`idanomalie`),
  CONSTRAINT `AETESCANNE_ibfk_2`
    FOREIGN KEY (`idronde`)
    REFERENCES `StationAccueil`.`Rondes` (`idronde`),
  CONSTRAINT `AETESCANNE_ibfk_3`
    FOREIGN KEY (`idagent`)
    REFERENCES `StationAccueil`.`Agents` (`idagent`),
  CONSTRAINT `AETESCANNE_ibfk_4`
    FOREIGN KEY (`idpointeau`)
    REFERENCES `StationAccueil`.`Pointeaux` (`idpointeau`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`Comporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`Comporte` (
  `idronde` INT NOT NULL,
  `idpointeau` INT NOT NULL,
  `ordre` INT NULL DEFAULT NULL,
  `tempsmini` TIME(4) NULL DEFAULT NULL,
  `tempsmaxi` TIME(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idronde`, `idpointeau`),
  INDEX `idpointeau` (`idpointeau` ASC),
  CONSTRAINT `COMPORTE_ibfk_1`
    FOREIGN KEY (`idpointeau`)
    REFERENCES `StationAccueil`.`Pointeaux` (`idpointeau`),
  CONSTRAINT `COMPORTE_ibfk_2`
    FOREIGN KEY (`idronde`)
    REFERENCES `StationAccueil`.`Rondes` (`idronde`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`Lieux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`Lieux` (
  `idlieux` INT NOT NULL,
  `batiment` VARCHAR(30) NULL DEFAULT NULL,
  `etage` VARCHAR(30) NULL DEFAULT NULL,
  `emplacement` VARCHAR(30) NULL DEFAULT NULL,
  `idpointeau` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idlieux`),
  INDEX `idpointeau` (`idpointeau` ASC),
  CONSTRAINT `LIEUX_ibfk_1`
    FOREIGN KEY (`idpointeau`)
    REFERENCES `StationAccueil`.`Pointeaux` (`idpointeau`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`PeutFaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`PeutFaire` (
  `idagent` INT NOT NULL,
  `idronde` INT NOT NULL,
  PRIMARY KEY (`idagent`, `idronde`),
  INDEX `idronde` (`idronde` ASC),
  CONSTRAINT `PEUTFAIRE_ibfk_1`
    FOREIGN KEY (`idronde`)
    REFERENCES `StationAccueil`.`Rondes` (`idronde`),
  CONSTRAINT `PEUTFAIRE_ibfk_2`
    FOREIGN KEY (`idagent`)
    REFERENCES `StationAccueil`.`Agents` (`idagent`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `StationAccueil`.`Responsables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StationAccueil`.`Responsables` (
  `idresponsable` INT NOT NULL,
  `nom` VARCHAR(30) NULL DEFAULT NULL,
  `prenom` VARCHAR(30) NULL DEFAULT NULL,
  `numbadge` VARCHAR(10) NULL DEFAULT NULL,
  `login` VARCHAR(60) NULL DEFAULT NULL,
  `mdp` VARCHAR(30) NULL DEFAULT NULL,
  `statut` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idresponsable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
